= Stretchly Settings
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:stretchly: https://hovancik.net/stretchly/[Stretchly]

My settings for the {stretchly} break timer.

== Usage

This repository contains the settings file for Stretchly.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.

. Clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/stretchly-settings.git
----

. Symlink the `config.json` file to the appropriate location.
+
--
NOTE: Close Stretchly before copying the settings file.

[,sh]
----
ln --relative --symbolic --force ~/Projects/stretchly-settings/config.json ~/.config/Stretchly/config.json
----
--

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[] file.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[] file.

== Copyright

© 2020-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
